version: 2

project_name: blogwatcher

builds:
  - id: blogwatcher
    main: ./cmd/blogwatcher
    binary: blogwatcher
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: windows
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
    ldflags:
      - -s -w -X github.com/Hyaxia/blogwatcher/internal/version.Version={{.Version}}

archives:
  - id: default
    builds:
      - blogwatcher
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

brews:
  - name: blogwatcher
    homepage: https://github.com/Hyaxia/blogwatcher
    description: Track blog articles and detect new posts.
    license: MIT
    directory: Formula
    repository:
      owner: Hyaxia
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "blogwatcher"
    test: |
      system "#{bin}/blogwatcher", "--version"
